Admin/Admin/urls.py
from django.contrib import admin
from django.urls import path, include, re_path

urlpatterns = [
    path('admin/', admin.site.urls),
    re_path('^', include('myapp.urls', namespace='continuous')),
]

Admin/myapp/urls.py
from django.urls import path, re_path

from myapp.views import *

app_name = 'myapp'

urlpatterns = [
    path('publisher_list/', publisher_list),
    path('add_publisher/', add_publisher),
    path('drop_publisher/', drop_publisher),
    path('edit_publisher/', edit_publisher),
    path('book_list/', book_list, name='booklist'),
    path('add_book/', add_book),
    path('drop_book/', drop_book),
    path('edit_book/', edit_book),
    path('author_list/', author_list, name='authorlist'),
    path('add_author/', add_author),
    path('drop_author/', drop_author),
    path('edit_author/', edit_author),
    re_path('^$', publisher_list),
]

Admin/myapp/models.py
from django.db import models

# Create your models here.
# 出版社类
class Publisher(models.Model):
    id = models.AutoField(primary_key=True)
    name = models.CharField(max_length=64)

# 书籍类
class Book(models.Model):
    id = models.AutoField(primary_key=True)
    name = models.CharField(max_length=64)
    publisher = models.ForeignKey(Publisher, on_delete=models.CASCADE)  # 创建外键

# 作者类
class Author(models.Model):
    id = models.AutoField(primary_key=True)
    name = models.CharField(max_length=64)
    # 一个作者对应多本书，一本书可以有多个作者，多对多，在数据库中创建第三张表
    book = models.ManyToManyField(Book, through='BookToAuthor')

class BookToAuthor(models.Model):
    book = models.ForeignKey(Book, on_delete=models.CASCADE)
    author = models.ForeignKey(Author, on_delete=models.CASCADE)

Admin/myapp/views.py
from django.http import HttpResponseRedirect
from django.shortcuts import render

from myapp.models import *

# 出版社列表
def publisher_list(request):
    # 查询
    publisher = Publisher.objects.all()
    return render(request, 'publisher_list.html', {'publisher_list':publisher})

# 添加出版社
def add_publisher(request):
    # POST方式提交数据
    if request.method == 'POST':
        new_publisher_name = request.POST.get('name')
        Publisher.objects.create(name=new_publisher_name)
        return HttpResponseRedirect('/publisher_list/')
    return render(request, 'add_publisher.html')

# 删除出版社
def drop_publisher(request):
    # get方式拿到出版社id
    drop_id = request.GET.get('id')
    drop_obj = Publisher.objects.get(id=drop_id)
    drop_obj.delete()
    return HttpResponseRedirect('/publisher_list/')

# 编辑出版社
def edit_publisher(request):
    if request.method == 'POST':
        edit_id = request.GET.get('id')
        edit_obj = Publisher.objects.get(id=edit_id)
        new_name = request.POST.get('name')
        edit_obj.name = new_name
        edit_obj.save()
        return HttpResponseRedirect('/publisher_list/')
    edit_id = request.GET.get('id')
    edit_obj = Publisher.objects.get(id=edit_id)
    return render(request, 'edit_publisher.html', {'publisher':edit_obj})

# 书籍列表
def book_list(request):
    book = Book.objects.all()
    return render(request, 'book_list.html', {'book_lish':book})

# 添加书籍
def add_book(request):
    if request.method == 'POST':
        new_book_name = request.POST.get('name')
        publisher_id = request.POST.get('publisher_id')
        Book.objects.create(name=new_book_name, publisher_id=publisher_id)
        return HttpResponseRedirect('/book_list/')
    msg = Publisher.objects.all()
    return render(request, 'add_book.html', {'publisher_list':msg})

# 删除书籍
def drop_book(request):
    drop_id = request.GET.get('id')
    drop_obj = Book.objects.get(id=drop_id)
    drop_obj.delete()
    return HttpResponseRedirect('/book_list/')

# 编辑书籍
def edit_book(request):
    if request.method == 'POST':
        new_book_name = request.POST.get('name')
        new_publisher_id = request.POST.get('publisher_id')
        edit_id = request.GET.get('id')
        edit_obj = Book.objects.get(id=edit_id)
        edit_obj.name = new_book_name
        edit_obj.publisher_id = new_publisher_id
        edit_obj.save()
        return HttpResponseRedirect('/book_list/')
    edit_id = request.GET.get('id')
    edit_obj = Book.objects.get(id=edit_id)
    all_publisher = Publisher.objects.all()
    return render(request, 'edit_book.html', {'book':edit_obj, 'publisher_list':all_publisher})

def author_list(request):
    author = Author.objects.all()
    return render(request, 'author_list.html', {'author_list':author})

# 添加作者
def add_author(request):
    if request.method == 'POST':
        new_author_name = request.POST.get('name')
        Author.objects.create(name=new_author_name)
        return HttpResponseRedirect('/author_list/')
    return render(request, 'add_author.html')

# 删除作者
def drop_author(request):
    drop_id = request.GET.get('id')
    drop_obj = Author.objects.get(id=drop_id)
    drop_obj.delete()
    return HttpResponseRedirect('/author_list/')

# 编辑作者
def edit_author(request):
    if request.method == 'POST':
        edit_id = request.GET.get('id')
        edit_obj = Author.objects.get(id=edit_id)
        new_author_name = request.POST.get('name')
        new_book_id = request.POST.getlist('book_id')
        edit_obj.name = new_author_name
        edit_obj.book.set(new_book_id)
        edit_obj.save()
        return HttpResponseRedirect('/author_list/')
    edit_id = request.GET.get('id')
    edit_obj = Author.objects.get(id=edit_id)
    all_book = Book.objects.all()
    return render(request, 'edit_author.html', {'author':edit_obj, 'book_list':all_book})

Admin/templates/add_author.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>新增作者</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="/static/bootstrap-3.3.7/css/bootstrap.min.css" rel="stylesheet">
    <link href="/static/fontawesome/css/font-awesome.min.css" rel="stylesheet">
</head>
<body>

<div class="container">
    <div class="row">
        <div class="page-header ">
            <h1 class="text-center">新增作者信息</h1>
            <div class="col-md-6 col-md-offset-3">
                <div class="panel panel-primary">
                    <div class="panel-heading">
                        <h3 class="panel-title">新增</h3>
                    </div>
                    <div class="panel-body">
                        <form class="form-horizontal" action="/add_author/" method="post">
                            <div class="form-group">
                                <label for="inputEmail3" class="col-sm-3 control-label">作者姓名</label>
                                <div class="col-sm-9">
                                    <input type="text" class="form-control" id="inputEmail3" name="name" placeholder="作者姓名">
                                </div>
                            </div>

                            <div class="form-group">
                                <div class="col-sm-offset-3 col-sm-9">
                                    <button type="submit" class="btn btn-default">提交</button>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
</body>
</html>

Admin/templates/add_book.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>添加书籍</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="/static/bootstrap-3.3.7/css/bootstrap.min.css" rel="stylesheet">
    <link href="/static/fontawesome/css/font-awesome.min.css" rel="stylesheet">
</head>
<body>

<div class="container">
    <div class="row">
        <div class="page-header ">
            <h1 class="text-center">新增书籍信息</h1>
            <div class="col-md-6 col-md-offset-3">
                <div class="panel panel-primary">
                    <div class="panel-heading">
                        <h3 class="panel-title">新增</h3>
                    </div>
                    <div class="panel-body">
                        <form class="form-horizontal" action="/add_book/" method="post">
                            <div class="form-group">
                                <label for="inputEmail3" class="col-sm-3 control-label">书籍名称</label>
                                <div class="col-sm-9">
                                    <input type="text" class="form-control" id="inputEmail3" name="name" placeholder="书籍名称">
                                </div>
                            </div>
                            <div class="form-group">
                                <label for="inputEmail3" class="col-sm-3 control-label">出版社名称</label>
                                <div class="col-sm-9">
                                    <select class="form-control" name="publisher_id">
                                        {% for publisher in publisher_list %}
                                        <option value="{{ publisher.id }}">{{ publisher.name }}</option>
                                        {% endfor %}
                                    </select>
                                </div>
                            </div>
                            <div class="form-group">
                                <div class="col-sm-offset-3 col-sm-9">
                                    <button type="submit" class="btn btn-default">提交</button>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
</body>
</html>

Admin/templates/add_publisher.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>添加出版社</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="/static/bootstrap-3.3.7/css/bootstrap.min.css" rel="stylesheet">
    <link href="/static/fontawesome/css/font-awesome.min.css" rel="stylesheet">
</head>
<body>

<div class="container">
    <div class="row">
        <div class="page-header ">
            <h1 class="text-center">新增出版社信息</h1>
            <div class="col-md-6 col-md-offset-3">
                <div class="panel panel-primary">
                    <div class="panel-heading">
                        <h3 class="panel-title">新增</h3>
                    </div>
                    <div class="panel-body">
                        <form class="form-horizontal" action="/add_publisher/" method="post">
                            <div class="form-group">
                                <label for="inputEmail3" class="col-sm-3 control-label">出版社名称</label>
                                <div class="col-sm-9">
                                    <input type="text" class="form-control" id="inputEmail3" name="name" placeholder="出版社名称">
                                </div>
                            </div>
                            <div class="form-group">
                                <div class="col-sm-offset-3 col-sm-9">
                                    <button type="submit" class="btn btn-default">提交</button>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
</body>
</html>

Admin/templates/author_list.html
<!DOCTYPE html>
<!-- saved from url=(0041)http://v3.bootcss.com/examples/dashboard/ -->
<html lang="zh-CN">
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- 上述3个meta标签*必须*放在最前面，任何其他内容都*必须*跟随其后！ -->
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="http://v3.bootcss.com/favicon.ico">
    <title>签约作家信息</title>
    <!-- Bootstrap core CSS -->
    <link href="/static/bootstrap-3.3.7/css/bootstrap.min.css" rel="stylesheet">
    <link href="/static/fontawesome/css/font-awesome.min.css" rel="stylesheet">
    <!-- Custom styles for this template -->
    <link href="/static/dashboard.css" rel="stylesheet">
    <link href="/static/my-style.css" rel="stylesheet">
</head>

<body>
<nav class="navbar navbar-inverse navbar-fixed-top">
    <div class="container-fluid">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#my-menu" aria-expanded="true" aria-controls="navbar">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="/publisher_list/">欢迎来到，伟昌图书管理系统</a>
        </div>
        <div id="navbar" class="navbar-collapse collapse" aria-expanded="true" style="">
            <ul class="nav navbar-nav">
                <li><a href="http://v3.bootcss.com/examples/dashboard/#">Dashboard</a></li>
                <li><a href="http://v3.bootcss.com/examples/dashboard/#">Settings</a></li>
                <li><a href="http://v3.bootcss.com/examples/dashboard/#">Profile</a></li>
                <li><a href="http://v3.bootcss.com/examples/dashboard/#">Help</a></li>
            </ul>
        </div>
    </div>
</nav>

<div class="container-fluid">
    <div class="row">
        <div class="col-sm-3 col-md-2 sidebar collapse" id="my-menu">
            <div class="my-menu-item" data-target="#menu-son1" data-toggle="collapse"><a>朝代检索</a></div>
            <ul class="nav nav-sidebar collapse" id="menu-son1">
                <li><a href="http://v3.bootcss.com/examples/dashboard/#">Overview</a></li>
                <li><a href="http://v3.bootcss.com/examples/dashboard/#">Reports</a></li>
                <li><a href="http://v3.bootcss.com/examples/dashboard/#">Analytics</a></li>
                <li><a href="http://v3.bootcss.com/examples/dashboard/#">Export</a></li>
            </ul>
            <div class="my-menu-item" href="#menu-son2" data-toggle="collapse"><a>姓名排序</a></div>
            <ul class="nav nav-sidebar collapse" id="menu-son2">
                <li><a href="http://v3.bootcss.com/examples/dashboard/">Nav item</a></li>
                <li><a href="http://v3.bootcss.com/examples/dashboard/">Nav item again</a></li>
                <li><a href="http://v3.bootcss.com/examples/dashboard/">One more nav</a></li>
                <li><a href="http://v3.bootcss.com/examples/dashboard/">Another nav item</a></li>
                <li><a href="http://v3.bootcss.com/examples/dashboard/">More navigation</a></li>
            </ul>
            <div class="my-menu-item" href="#menu-son3" data-toggle="collapse"><a>世界著名作家</a></div>
            <ul class="nav nav-sidebar collapse" id="menu-son3">
                <li><a href="http://v3.bootcss.com/examples/dashboard/">Nav item again</a></li>
                <li><a href="http://v3.bootcss.com/examples/dashboard/">One more nav</a></li>
                <li><a href="http://v3.bootcss.com/examples/dashboard/">Another nav item</a></li>
            </ul>
        </div>
        <div class="col-sm-9 col-sm-offset-3 col-md-10 col-md-offset-2 main">
            <h1 class="page-header">作者管理系统</h1>
            <!-- 面板开始 -->
            <div class="panel panel-primary">
                <div class="panel-heading">
                    <h3 class="panel-title">作者管理</h3>
                </div>
                <div class="panel-body">
                    <!--表格 工具栏 开始-->
                    <div class="row table-toolbar">
                        <div class="col-md-3 col-sm-6">
                            <div class="input-group">
                                <input type="text" class="form-control" placeholder="Search for...">
                                <span class="input-group-btn">
                                    <button class="btn btn-default" type="button">Go!</button>
                                </span>
                            </div><!-- /input-group -->
                        </div><!-- /.col-lg-6 -->
                        <div class="col-md-3 col-sm-6 pull-right add-btn">
                            <button data-target="#myModal" data-toggle="modal" class="btn btn-success pull-right">新增
                            </button>
                            <a href="/add_author/" class="btn btn-info pull-right">新页面添加</a>
                        </div>
                    </div>
                    <!--表格 工具栏 结束-->
                    <table class="table table-striped table-bordered">
                        <thead>
                        <tr>
                            <th>序号</th>
                            <th>作者姓名</th>
                            <th>著作</th>
                            <th>操作</th>
                        </tr>
                        </thead>
                        <tbody>
                            {% for author in author_list %}
                            <tr>
                                <td>{{ forloop.counter }}</td>
                                <td>{{ author.name }}</td>
                                <td>{% for book in author.book.all %}
                                    {% if forloop.last %}
                                        《{{ book.name }}》
                                    {% else %}
                                        《{{ book.name }}》,
                                    {% endif %}
                                    {% empty %}
                                    暂无著作
                                {% endfor %}
                                </td>
                                <td class="text-center">
                                    <a class="btn btn-info btn-sm" href="/edit_author/?id={{ author.id }}"><i class="fa fa-pencil fa-fw" aria-hidden="true"></i>编辑</a>
                                    <a class="btn btn-danger btn-sm" href="/drop_author/?id={{ author.id }}"><i class="fa fa-trash-o fa-fw" aria-hidden="true"></i>删除</a>
                                </td>
                            </tr>
                            {% endfor %}
                        </tbody>
                    </table>
                    <!--分页 开始-->
                    <div>
                        <nav aria-label="Page navigation" class="pull-right">
                            <ul class="pagination">
                                <li>
                                    <a href="#" aria-label="Previous">
                                        <span aria-hidden="true">&laquo;</span>
                                    </a>
                                </li>
                                <li><a href="#">1</a></li>
                                <li><a href="#">2</a></li>
                                <li><a href="#">3</a></li>
                                <li><a href="#">4</a></li>
                                <li><a href="#">5</a></li>
                                <li>
                                    <a href="#" aria-label="Next">
                                        <span aria-hidden="true">&raquo;</span>
                                    </a>
                                </li>
                            </ul>
                        </nav>
                    </div>
                    <!--分页 结束-->
                </div>
            </div>
            <!-- 面板 结束-->
        </div>
    </div>
</div>
<!--模态框开始-->
<div class="modal fade" tabindex="-1" role="dialog" id="myModal">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <h4 class="modal-title">添加新信息</h4>
            </div>
            <div class="modal-body">
                <form class="form-horizontal">
                    <div class="form-group">
                        <label for="inputEmail3" class="col-sm-3 control-label">出版社名称</label>
                        <div class="col-sm-9">
                            <input type="text" class="form-control" id="inputEmail3" placeholder="名称">
                        </div>
                    </div>
                    <div class="form-group">
                        <label for="addr" class="col-sm-3 control-label">出版社地址</label>
                        <div class="col-sm-9">
                            <textarea id="addr" class="form-control" rows="3"></textarea>
                        </div>
                    </div>
                </form>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">取消</button>
                <button type="button" class="btn btn-primary">保存</button>
            </div>
        </div><!-- /.modal-content -->
    </div><!-- /.modal-dialog -->
</div><!-- /.modal -->
<!--模态框结束-->
<!-- Bootstrap core JavaScript
================================================== -->
<!-- Placed at the end of the document so the pages load faster -->
<script src="/static/jquery-3.3.1.min.js"></script>
<script src="/static/bootstrap-3.3.7/js/bootstrap.min.js"></script>

</body>
</html>

Admin/templates/publisher_list.html
<!DOCTYPE html>
<!-- saved from url=(0041)http://v3.bootcss.com/examples/dashboard/ -->
<html lang="zh-CN">
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- 上述3个meta标签*必须*放在最前面，任何其他内容都*必须*跟随其后！ -->
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="http://v3.bootcss.com/favicon.ico">
    <title>图书管理系统</title>
    <!-- Bootstrap core CSS -->
    <link href="/static/bootstrap-3.3.7/css/bootstrap.min.css" rel="stylesheet">
    <link href="/static/fontawesome/css/font-awesome.min.css" rel="stylesheet">
    <!-- Custom styles for this template -->
    <link href="/static/dashboard.css" rel="stylesheet">
    <link href="/static/my-style.css" rel="stylesheet">
</head>

<body>
<nav class="navbar navbar-inverse navbar-fixed-top">
    <div class="container-fluid">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#my-menu"
                    aria-expanded="true"
                    aria-controls="navbar">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="#">欢迎来到，伟昌图书管理系统</a>
        </div>
        <div id="navbar" class="navbar-collapse collapse" aria-expanded="true" style="">
            <ul class="nav navbar-nav">
                <li><a href="#">首页</a></li>
                <li><a href="#">资源</a></li>
                <li><a href="#">续借</a></li>
                <li><a href="#">服务</a></li>
                <li><a href="#">关于我们</a></li>
                <li><a href="#">设置</a></li>
            </ul>
        </div>
    </div>
</nav>
<div class="container-fluid">
    <div class="row">
        <div class="col-sm-3 col-md-2 sidebar collapse" id="my-menu">
            <div class="my-menu-item" data-target="#menu-son1" data-toggle="collapse"><a>馆藏目录</a></div>
            <ul class="nav nav-sidebar collapse" id="menu-son1">
                <li><a href="#">历史</a></li>
                <li><a href="#">文学</a></li>
                <li><a href="#">地理</a></li>
                <li><a href="#">人工智能</a></li>
                <li><a href="#">动漫</a></li>
                <li><a href="#">生活</a></li>
            </ul>
            <div class="my-menu-item" href="#menu-son2" data-toggle="collapse"><a>电子期刊</a></div>
            <ul class="nav nav-sidebar collapse" id="menu-son2">
                <li><a href="https://wdzxyjsj.xueshu.com/" target="_blank">微电子学与计算机</a></li>
                <li><a href="https://wxtxjs.xueshu.com/" target="_blank">无线通信技术</a></li>
                <li><a href="https://dnkfyyy.xueshu.com/" target="_blank">电脑开发与应用</a></li>
                <li><a href="https://jsjjsyfz.xueshu.com/" target="_blank">计算机技术与发展</a></li>
                <li><a href="https://hkjsjs.xueshu.com/" target="_blank">航空计算技术</a></li>
            </ul>
            <div class="my-menu-item" href="#menu-son3" data-toggle="collapse"><a>报刊专栏</a></div>
            <ul class="nav nav-sidebar collapse" id="menu-son3">
                <li><a href="http://www.people.com.cn/" target="_blank">人民日报</a></li>
                <li><a href="http://www.xiancn.com/quality/duzhefw.html" target="_blank">西安日报</a></li>
                <li><a href="http://www.sanqin.com/" target="_blank">三秦数字报</a></li>
            </ul>
        </div>
        <div class="col-sm-9 col-sm-offset-3 col-md-10 col-md-offset-2 main">
            <h1 class="page-header">图书信息管理系统</h1>
            <!-- 面板开始 -->
            <div class="panel panel-primary">
                <div class="panel-heading">
                    <h3 class="panel-title">出版社管理</h3>
                </div>
                <div class="panel-body">
                    <!--表格 工具栏 开始-->
                    <div class="row table-toolbar">
                        <div class="col-md-3 col-sm-6">
                            <div class="input-group">
                                <input type="text" class="form-control" placeholder="Search for...">
                                <span class="input-group-btn">
                                    <button class="btn btn-default" type="button">Go!</button>
                                </span>
                            </div><!-- /input-group -->
                        </div><!-- /.col-lg-6 -->
                        <div class="col-md-3 col-sm-6 pull-right add-btn">
                            <button data-target="#myModal" data-toggle="modal" class="btn btn-success pull-right"><a href="{% url 'continuous:booklist' %}">图书管理</a></button>
                            <button data-target="#myModal" data-toggle="modal" class="btn btn-success pull-right"><a href="{% url 'continuous:authorlist' %}">管理作者信息</a></button>
{#                            <button data-target="#myModal" data-toggle="modal" class="btn btn-info pull-right">新增</button>#}
                            <a href="/add_publisher/" class="btn btn-info pull-right">新页面添加</a>
                        </div>
                    </div>
                    <!--表格 工具栏 结束-->
                    <table class="table table-striped table-bordered">
                        <thead>
                        <tr>
                            <th>序号</th>
                            <th>出版社名称</th>
                            <th>操作</th>
                        </tr>
                        </thead>
                        <tbody>
                        {% for publisher in publisher_list %}
                            <tr>
                                <td>{{ forloop.counter }}</td>
                                <td>{{ publisher.name }}</td>
                                <td class="text-center">
                                    <a class="btn btn-info btn-sm" href="/edit_publisher/?id={{ publisher.id }}"><i class="fa fa-pencil fa-fw" aria-hidden="true"></i>编辑</a>
                                    <a class="btn btn-danger btn-sm" href="/drop_publisher/?id={{ publisher.id }}"><i class="fa fa-trash-o fa-fw" aria-hidden="true"></i>删除</a>
                                </td>
                            </tr>
                        {% endfor %}
                        </tbody>
                    </table>
                    <!--分页 开始-->
                    <div>
                        <nav aria-label="Page navigation" class="pull-right">
                            <ul class="pagination">
                                <li>
                                    <a href="#" aria-label="Previous">
                                        <span aria-hidden="true">&laquo;</span>
                                    </a>
                                </li>
                                <li><a href="#">1</a></li>
                                <li><a href="#">2</a></li>
                                <li><a href="#">3</a></li>
                                <li><a href="#">4</a></li>
                                <li><a href="#">5</a></li>
                                <li>
                                    <a href="#" aria-label="Next">
                                        <span aria-hidden="true">&raquo;</span>
                                    </a>
                                </li>
                            </ul>
                        </nav>
                    </div>
                    <!--分页 结束-->
                </div>
            </div>
            <!-- 面板 结束-->
        </div>
    </div>
</div>
<!--模态框开始-->
<div class="modal fade" tabindex="-1" role="dialog" id="myModal">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <h4 class="modal-title">添加新信息</h4>
            </div>
            <div class="modal-body">
                <form class="form-horizontal">
                    <div class="form-group">
                        <label for="inputEmail3" class="col-sm-3 control-label">出版社名称</label>
                        <div class="col-sm-9">
                            <input type="text" class="form-control" id="inputEmail3" placeholder="名称">
                        </div>
                    </div>
                    <div class="form-group">
                        <label for="addr" class="col-sm-3 control-label">出版社地址</label>
                        <div class="col-sm-9">
                            <textarea id="addr" class="form-control" rows="3"></textarea>
                        </div>
                    </div>
                </form>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">取消</button>
                <button type="button" class="btn btn-primary">保存</button>
            </div>
        </div><!-- /.modal-content -->
    </div><!-- /.modal-dialog -->
</div><!-- /.modal -->
<!--模态框结束-->

<!-- Bootstrap core JavaScript
================================================== -->
<!-- Placed at the end of the document so the pages load faster -->
<script src="/static/jquery-3.3.1.min.js"></script>
<script src="/static/bootstrap-3.3.7/js/bootstrap.min.js"></script>

</body>
</html>